CREATE TABLE GIOHANG 
(
	Username VARCHAR(50) REFERENCES TAIKHOAN(Username),
	ThanhTien FLOAT
)

CREATE TABLE CHITIETGIOHANG
(
	Username VARCHAR(50) REFERENCES TAIKHOAN(Username),
	MaHang VARCHAR(10) REFERENCES MATHANG(MaHang),
	SoLuong INT,
	TongTien FLOAT
)