CREATE TABLE DANHMUC
(
	MaDanhMuc NVARCHAR(10) NOT NULL PRIMARY KEY,
	TenDanhMuc NVARCHAR(50),
	MoTa NVARCHAR(50)
)

CREATE TABLE MATHANG
(
	MaHang NVARCHAR(10) NOT NULL PRIMARY KEY,
	TenHang NVARCHAR(50),
	SoLuong INT,
	HinhAnh NVARCHAR(100),
	Gia FLOAT,
	MoTa NVARCHAR(50),
	MaDanhMuc NVARCHAR(10) REFERENCES DANHMUC(MaDanhMuc)
)

CREATE TABLE TAIKHOAN
(
	Username NVARCHAR(50) NOT NULL PRIMARY KEY,
	HoTen NVARCHAR(50),
	Email NVARCHAR(50),
	SDT NVARCHAR(15),
	DiaChi NVARCHAR(50),
	GioiTinh BIT,
	QuocTich NVARCHAR(50),
	MatKhau NVARCHAR(50),
	IsAdmin BIT
)

CREATE TABLE HOADON
(
	MaHoaDon NVARCHAR(10) NOT NULL PRIMARY KEY,
	Username NVARCHAR(50) REFERENCES TAIKHOAN(Username),
	TongTien FLOAT,
	NgayXuat DATE
)

CREATE TABLE CHITIETHOADON
(
	MaHoaDon NVARCHAR(10) NOT NULL,
	MaHang NVARCHAR(10) NOT NULL,
	SoLuong INT,
	DonGia FLOAT,
	ThanhTien FLOAT
)
